artifacts:
    sqlite: org.xerial:sqlite-jdbc:jar:3.6.16     
    pircbot: pircbot:pircbot:jar:1.4.2
    jdom: org.jdom:jdom:jar:1.1
    tagsoup: org.ccil.cowan.tagsoup:tagsoup:jar:1.1.3
    jaxen: jaxen:jaxen:jar:1.1.1
    jchardet: net.sourceforge.jchardet:jchardet:jar:1.0
